### PR TITLE
WIP: Migrate to PySide6 / Qt6

### LINKED ISSUE #63: .ui to .py file conversion problem
Currently the `.py` files are not part of the repository and must be generated after checkout using `make build-ui`, this approach was chosen to avoid checking in generated files.

This approach introduces the drawback that an additional step is needed to run the app. Best case we find a way to use the `.ui` files directly within python so no additional (`make`) step is needed ...

### LINKED ISSUE #93: Move to Qt6
Qt5 are EOL (https://en.wikipedia.org/wiki/Qt_version_history)
Only Qt6 are supported without any commercial licence.

### PR DESCRIPTION
**Pull request by daringer**
Migrates Qt5 directly to PySide6/Qt6 and replaces pre-compiled ui/resource files with it's runtime equivalents.

**can be tested**

todos:
* windows tests
* format/typing
* squash
* layout details

done:
* renamed imports from PyQt5 to PySide6
* renamed all `pyqtSignal`/`pyqtSlot` to the new names `Signal`/`Slot`
* removed any remaining `.ui` + resource management, directly loading all from file during runtime now
* various fixes for ui-loading in combination with deriving from `Q*`-stuff (i.e., widgets now auto-resizing as intended)
* removed recursion as Qt doesn't like its `.connect` method overwritten
 * (all??) the needed enum renames are done using [this script](https://stackoverflow.com/questions/72086632/migrating-to-qt6-pyqt6-what-are-all-the-deprecated-short-form-names-in-qt5)
* random-walk tests on linux from repository/source only

fixes #93, fixes #63, fixes #163

### CODE REVIEW

**Comment by mmerklinger** [comment]
We also need to test the builds manually for all platforms and make sure the build environments in the pipelines have all necessary dependencies. Though I would suggest to first fix the functional problems and then move on to deployment.

**Comment by mmerklinger** [comment]
Can we maybe also move to only using UI files as of #63 with this change?

**Comment by daringer** [comment]
clearly the right PR to do such a change, will look into it

**Comment by mmerklinger** [comment]
# Linux

## pyinstaller - onefile

- Nitrokey-Logo on the top left missing
- Icons on the bottom left for Home and Help missing
- On the Homepage the big Nitrokey logo in the middle is missing
- The Nitrokey icon in front of a connected Nitrokey works
- On the password tab the lock/unlock icon in the list works
- On the *add password* window the CANCEL an OK buttons work

## pyinstaller - onedir

- If executed from within the directory the icons work, if from different directory they do not
- The Nitrokey icon on the top left is not centered

**Comment by mmerklinger** [comment]
# Windows

## pyinstaller - onefile

- Nitrokey-Logo on the top left missing
- Icons on the bottom left for Home and Help missing
- On the Homepage the big Nitrokey logo in the middle is missing
- The Nitrokey icon in front of a connected Nitrokey works
- On the overview tab the lock/unlock icon in the list works
- On the password window the CANCEL an OK button missing (maybe usually not shown on Windows?)

## pyinstaller - onedir

- If executed from within the directory the icons work, if from different directory they do not
- The Nitrokey icon on the top left is centered, but the button for the connected Nitrokey is very closely under it

**Comment by daringer** [comment]
closing in favor of: https://github.com/Nitrokey/nitrokey-app2/pull/187

**Pull request closed without merging**
