### PR TITLE
Refactor device detection to work with any OS

### LINKED ISSUE #252: macOS: auto-detection (add/remove device) not working properly
simply not implemented, use `usb-monitor` for this

### PR DESCRIPTION
**Pull request by daringer**
This refactors the triggering/hooking part of the new-device-detection to use some OS agnostic mechanism.
`usb-monitor` is the way to go - please provide test reports for any OS with a procedure essentially like that:

* start with connected nk3
* 1x nk3 should be visible
* disconnect the nk3 - nk3 should vanish
* connect the nk3 - nk3 should come up in <2secs

fixes #252

### CODE REVIEW

**Review by jj-so — COMMENTED** [review]
works on Windows. password safe works
-> update function not fully tested

**Comment by mmerklinger** [comment]
Tested on macOS (ARM64). Device recognition works without issues.

**Comment by robin-nitrokey** [comment]
AFAIS this also allows us to remove the `pyudev` dependency.

**Comment by daringer** [comment]
right, done here: #272

**Pull request merged**
